Sur-284 template onboarding Forms
brainstormforce/force-ui pull request #119
Opened 2024-10-08 12:12 UTC by BabuTechBsf

### Description

Added Form Screens

### Screenshots

https://d.pr/i/Ke5Gwa
https://d.pr/i/y11e6p

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-10-09 07:56 UTC, jaieds requested changes
- Fix overall padding and gap.
- Fix the navigation background color.
- Fix content container width. Currently, it's taking full width.

**Screenshot:** https://d.pr/i/Y8uoyo

2024-10-09 11:18 UTC, JelenaTakac reviewed
I noticed some mismatches with the design mockup. Could you please check the screenshots for details?
Screenshots: https://bsf.d.pr/i/coYTK1 | https://bsf.d.pr/i/K9eisl

2024-10-09 16:03 UTC, HimanshuSangale commented
- Everything present in form can be included in a grid instead of just input fields.
- Padding of 8px needed inside each grid element and buttons container at bottom - https://d.pr/i/JUngta
- Back, skip and next button layout can be improved using flex-grow property on latter 2 buttons - https://d.pr/i/RvMgm4
- Skip can be made a button of type ghost - https://d.pr/i/qtJJHM

2024-10-12 19:16 UTC, JelenaTakac reviewed
Please check screenshot: https://bsf.d.pr/i/J32kF8

2024-10-12 19:50 UTC, BabuTechBsf commented
> Please check screenshot: https://bsf.d.pr/i/J32kF8

Skipped: 1. Component level change. 2. 2nd Is content as per last discussion text not need to match.

2024-10-12 21:50 UTC, ravindra114 requested changes

2024-10-12 21:50 UTC, ravindra114 commented on src/templates/onboarding-profile/onboarding-profile.stories.js
> +					<div className="flex justify-between items-center gap-6 mt-8">
can use container component instead of div?

2024-10-12 21:50 UTC, ravindra114 commented on src/templates/onboarding-social/onboarding-social.stories.js
> +				<div className="md:w-[45rem] box-border mx-auto p-8 mt-10 border border-solid border-border-subtle bg-background-primary rounded-md">
can use container component instead of div?

2024-10-13 13:22 UTC, JelenaTakac approved these changes

2024-10-14 05:22 UTC, jaieds requested changes
Please check below screenshots:
1. https://d.pr/i/Tsx8Sz
2. https://d.pr/i/y67klL

2024-10-14 07:07 UTC, ravindra114 approved these changes

2024-10-14 11:06 UTC, HimanshuSangale approved these changes

2024-10-14 12:40 UTC, vrundakansara commented
This PR is covered here - https://github.com/brainstormforce/force-ui/pull/131

2024-10-14 12:40 UTC, closed without merging