SUR-285 Template: Implement Dashbaords
brainstormforce/force-ui pull request #124
Opened 2024-10-10 08:12 UTC by JelenaTakac

### Description

### Screenshots

- https://bsf.d.pr/v/lRNyDP

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-10-10 11:20 UTC, HimanshuSangale requested changes
- Positioning of items can be improved by adding icons and badge in one container and text in another. Gap of 12px needed between the 2 container. https://d.pr/i/K1NAwp, https://d.pr/i/kLsUqE
- More spacing needed between menu icons. https://d.pr/i/LaNn5r
- Overall padding and alignment needs improvement in the hero card. https://d.pr/i/J3yfvn

2024-10-10 12:24 UTC, vrundakansara requested changes

2024-10-10 12:24 UTC, vrundakansara commented on src/templates/dashboard-astra/astraVideo.png
Can you use any image with same size here, which is remote URL, instead of actually saving the image?

2024-10-10 12:24 UTC, vrundakansara commented on src/templates/dashboard-spectra/contentImageSpectra.png
Same for this file too

2024-10-10 14:18 UTC, JelenaTakac commented
> * Positioning of items can be improved by adding icons and badge in one container and text in another. Gap of 12px needed between the 2 container. https://d.pr/i/K1NAwp, https://d.pr/i/kLsUqE

@BabuTechBsf this refers to the Radio Buttons used in this card. Can you give some insight on how to solve this?

2024-10-11 05:47 UTC, jaieds requested changes
@JelenaTakac, There some mismatch with the Figma, I've shared my feedback in the video. Please check.

1. https://share.cleanshot.com/kxvgrwgk
2. https://share.cleanshot.com/TKx6LzCh

2024-10-11 08:43 UTC, JelenaTakac commented on src/templates/dashboard-spectra/contentImageSpectra.png
Resolved.

2024-10-11 10:13 UTC, JelenaTakac commented
> @JelenaTakac, There some mismatch with the Figma, I've shared my feedback in the video. Please check.
> 
> 1. https://share.cleanshot.com/kxvgrwgk
> 2. https://share.cleanshot.com/TKx6LzCh

I pushed changes, please check it.

2024-10-11 10:14 UTC, JelenaTakac commented
> * Positioning of items can be improved by adding icons and badge in one container and text in another. Gap of 12px needed between the 2 container. https://d.pr/i/K1NAwp, https://d.pr/i/kLsUqE
> * More spacing needed between menu icons. https://d.pr/i/LaNn5r
> * Overall padding and alignment needs improvement in the hero card. https://d.pr/i/J3yfvn

I pushed changes, please check it.

2024-10-11 10:38 UTC, ravindra114 commented on src/components/badge/badge.jsx
> +		xxs: '[&>svg]:size-3',
add this in story book

2024-10-11 10:42 UTC, ravindra114 requested changes

2024-10-11 10:42 UTC, ravindra114 commented on src/components/badge/badge.jsx
>  		'group relative justify-center flex items-center [&>svg]:h-4 [&>svg]:w-4 cursor-pointer';
[&>svg]:h-4 [&>svg]:w-4 -> [&>svg]:size-4

2024-10-11 10:42 UTC, ravindra114 commented on src/components/badge/badge.jsx
>  		'group relative justify-center flex items-center [&>svg]:h-4 [&>svg]:w-4 cursor-pointer';
Can you move svgs in global icons?

2024-10-11 12:01 UTC, BabuTechBsf requested changes
- use decorators and increase the width for Good View
- Icons use existing global icons.. only create new if required.
- topbar links should be a tags (instead buttons) - use ‘#’ and target - _self.
- let’s not import/use so many icons use one or two and repeat. keep it as same for now.

2024-10-11 13:03 UTC, HimanshuSangale approved these changes

2024-10-11 14:14 UTC, JelenaTakac commented
> * use decorators and increase the width for Good View
> * Icons use existing global icons.. only create new if required.
> * topbar links should be a tags (instead buttons) - use ‘#’ and target - _self.
> * let’s not import/use so many icons use one or two and repeat. keep it as same for now.

@BabuTechBsf  I resolved issues, can you please check it.

2024-10-11 14:41 UTC, jaieds requested changes
1. UI looks broken/not good on a larger screen. https://d.pr/v/1xe9Hf
2. Use anchor tag. https://d.pr/i/tu9tWi

2024-10-11 14:42 UTC, jaieds commented on package.json
> +    "@tailwindcss/container-queries": "^0.1.1",
Install as dev-dependency.

2024-10-11 15:52 UTC, JelenaTakac commented on package.json
> +    "@tailwindcss/container-queries": "^0.1.1",
Installed.

2024-10-11 15:56 UTC, JelenaTakac commented
> 1. UI looks broken/not good on a larger screen. https://d.pr/v/1xe9Hf
> 2. Use anchor tag. https://d.pr/i/tu9tWi

Added max-width for content container. Implement anchor tag per you suggested for all, instead for this: https://bsf.d.pr/i/WTMMTK (per design it is a button component)

2024-10-12 07:37 UTC, BabuTechBsf approved these changes

2024-10-12 07:37 UTC, BabuTechBsf commented on src/templates/dashboard-spectra/dashboard-spectra.stories.js
> +	const radioButtonGroupData = defaultRadioButtonGroupData;
you can change your object name itself. any reason to re assign. check in other places too.

2024-10-14 04:45 UTC, vrundakansara approved these changes

2024-10-14 04:45 UTC, merged