Sur-228 dropzone
brainstormforce/force-ui pull request #187
Opened 2024-11-08 17:04 UTC by BabuTechBsf

### Description

Added Dropzone component

### Screenshots

https://d.pr/v/SF3oYt

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-11-11 08:33 UTC, jaieds commented on src/components/dropzone/dropzone.stories.tsx
> +			defaultValue: 'sm',
We should not define these manually.
```suggestion
```

2024-11-11 08:47 UTC, jaieds requested changes
- Add transition on hover.
- Fix gap and alignment. Screenshot: https://d.pr/i/Ky0zKA
- Fix the loader background. Screenshot: https://d.pr/i/o3Ng5F
- Focus state border is not present.
- Showing infinite loader. Screencast: https://d.pr/v/KAtPTq

2024-11-11 09:44 UTC, BabuTechBsf commented on src/components/dropzone/dropzone.stories.tsx
> +			defaultValue: 'sm',
My bad. Resolved.

2024-11-11 09:55 UTC, JelenaTakac requested changes
Please check video: https://bsf.d.pr/v/NYPjEe
In video mentioned some suggestions for improvements.

2024-11-11 10:35 UTC, BabuTechBsf commented
> * Add transition on hover.
> * Fix gap and alignment. Screenshot: https://d.pr/i/Ky0zKA
> * Fix the loader background. Screenshot: https://d.pr/i/o3Ng5F
> * Focus state border is not present.
> * Showing infinite loader. Screencast: https://d.pr/v/KAtPTq

Transition added.
Gaps is not given, Alignment adjusted.
background removed from component level.
focus state added.
loading fixed.

2024-11-11 10:37 UTC, BabuTechBsf commented
> Please check video: https://bsf.d.pr/v/NYPjEe In video mentioned some suggestions for improvements.

As per discussion with sujay on previous SRM. 
At this version we are not providing multi selection. 
Also loader was mentioned to be fake loader. So it's not a real loader of progress.
other issues fixed.

2024-11-12 06:13 UTC, jaieds commented on src/components/dropzone/dropzone.stories.tsx
> +import { Meta, StoryFn } from '@storybook/react';
```suggestion
import type { Meta, StoryFn } from '@storybook/react';
```

2024-11-12 08:52 UTC, merged