SUR-248 Implement a Container Component
brainstormforce/force-ui pull request #34
Opened 2024-08-19 12:14 UTC by JelenaTakac

### Description

# Container

## Description

The `Container` component is a flexible layout component that can be used to create grid or flexbox-based layouts.

## `Container` Props

### containerType
- **Type:** `string`
- **Default:** `"grid"`
- **Description:** Specifies the type of container
    - `"flex"`
    - `"grid"`

### gap
- **Type:** `string`
- **Description:** Defines the gap between grid or flex items.
    - `"xs"`
    - `"sm"`
    - `"md"`
    - `"lg"`
    - `"xl"`
    - `"2xl"`

### direction
- **Type:** `string`
- **Default:** `"row"`
- **Description:** Defines the direction of flex items (applicable only for flex containers).
    - `"row"`
    - `"row-reverse"`
    - `"column"`
    - `"column-reverse"`

### justify
- **Type:** `string`
- **Default:** `"start"`
- **Description:** Specifies how flex items are aligned along the main axis.
    - `"normal"`
    - `"start"`
    - `"end"`
    - `"center"`
    - `"between"`
    - `"around"`
    - `"evenly"`
    - `"stretch"`

### align
- **Type:** `string`
- **Default:** `"stretch"`
- **Description:** Specifies how flex items are aligned along the cross axis.
    - `"start"`
    - `"end"`
    - `"center"`
    - `"baseline"`
    - `"stretch"`

### wrap
- **Type:** `string`
- **Default:** `nowrap`
- **Description:** Defines how flex items should wrap in the container.
    - `"nowrap"`
    - `"wrap"`
    - `"wrap-reverse"`

### className
- **Type:** `string`
- **Description:** Additional custom classes to be added to the container.

### children
- **Type:** `ReactNode`
- **Description:** The content to be rendered inside the container.

### extraProps
- **Type:** `object`
- **Description:** Additional props to be passed to the container's root element.

## `Container.Item` Props

### grow
- **Type:** `number`
- **Description:** Specifies how much a flex item should grow relative to the rest of the flex items.
    - `"0"`
    - `"1"`

### shrink
- **Type:** `number`
- **Description:** Specifies how much a flex item should shrink relative to the rest of the flex items.
    - `"0"`
    - `"1"`

### order
- **Type:** `string`
- **Description:** Defines the order of the flex item in the container.
    - `"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"`
    - `"first"`
    - `"last"`
    - `"none"`

### alignSelf
- **Type:** `string`
- **Description:** Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items.
    - `"auto"`
    - `"start"`
    - `"end"`
    - `"stretch"`
    - `"baseline"`

## Usage

### Basic Example

```jsx
import { Container } from '@bsf/force-ui';

const App = () => (
    <Container containerType="flex" justify="end" align="start" gap="xs" className="bg-orange-300 h-60">
        <Container.Item grow={1}>Item 1</Container.Item>
        <Container.Item>Item 2</Container.Item>
        <Container.Item grow={1}>Item 3</Container.Item>
    </Container>
);

export default App;
```

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-08-19 12:40 UTC, vrundakansara commented
@JelenaTakac - Fix the lint pipeline by running `npm run lint:js-fix`.
Also push the code with the build - `npm run build`.

2024-08-19 13:03 UTC, vrundakansara requested changes

2024-08-19 13:03 UTC, vrundakansara commented on src/components/container/container.jsx
> +		containerType = 'grid', // flex, grid
Default should be flex

2024-08-19 13:03 UTC, vrundakansara commented on src/components/container/container.jsx
> +		gap, // xs, sm, md, lg, xl, 2xl
Keep `sm` as default

2024-08-19 13:03 UTC, vrundakansara commented on src/components/container/container.jsx
> +		align = 'stretch', // align-items (start, end, center, baseline, stretch)
Set it to blank as default

2024-08-19 13:03 UTC, vrundakansara commented on src/components/container/container.jsx
> +		justify = 'start', // justify-content (normal, start, end, center, between, around, evenly, stretch)
Blank as default

2024-08-19 13:03 UTC, vrundakansara commented on src/components/container/container.jsx
> +		direction = 'row', // row, row-reverse, column, column reverse
Blank as default

2024-08-19 14:22 UTC, jaieds commented on src/components/container/container.jsx
> +		extraProps,
```suggestion
		...extraProps,
```

2024-08-19 15:58 UTC, vrundakansara requested changes

2024-08-19 15:58 UTC, vrundakansara commented on dist/utils/withTW.js
Any reason why we deleted this file?

2024-08-20 05:56 UTC, JelenaTakac commented on dist/utils/withTW.js
@vrundakansara, can you please check it now?

2024-08-20 06:05 UTC, vrundakansara approved these changes

2024-08-20 07:39 UTC, jaieds approved these changes

2024-08-20 08:06 UTC, merged