SUR-252 Responsive Implementation for Container component ( Responsive Flexbox )
brainstormforce/force-ui pull request #37
Opened 2024-08-26 13:31 UTC by JelenaTakac

### Description

# Container

## Description

The `Container` component is a flexible layout component that can be used to create grid or flexbox-based layouts.

## `Container` Props

### containerType
- **Type:** `string`
- **Default:** `"flex"`
- **Description:** Specifies the type of container
    - `"flex"`
    - `"grid"`

### gap
- **Type:** `string`
- **Default:** `"sm"`
- **Description:** Defines the gap between grid or flex items.
    - `"xs"`
    - `"sm"`
    - `"md"`
    - `"lg"`
    - `"xl"`
    - `"2xl"`

### direction
- **Type:** `string`
- **Default:** `""`
- **Description:** Defines the direction of flex items (applicable only for flex containers).
    - `"row"`
    - `"row-reverse"`
    - `"column"`
    - `"column-reverse"`

### justify
- **Type:** `string`
- **Default:** `""`
- **Description:** Specifies how flex items are aligned along the main axis.
    - `"normal"`
    - `"start"`
    - `"end"`
    - `"center"`
    - `"between"`
    - `"around"`
    - `"evenly"`
    - `"stretch"`

### align
- **Type:** `string`
- **Default:** `""`
- **Description:** Specifies how flex items are aligned along the cross axis.
    - `"start"`
    - `"end"`
    - `"center"`
    - `"baseline"`
    - `"stretch"`

### wrap
- **Type:** `string`
- **Description:** Defines how flex items should wrap in the container. If no wrap is specified, it will automatically wrap if any column props (cols, tabCols, mCols) are provided.
    - `"nowrap"`
    - `"wrap"`
    - `"wrap-reverse"`

### cols
- **Type:** `string`
- **Default:** `""`
- **Description:** Specifies the number of columns for desktop view (applies to flexbox layouts). The column width is dynamically calculated based on the number of columns and the gap size.

### tabCols
- **Type:** `string`
- **Default:** `""`
- **Description:** Specifies the number of columns for tablet view (applies to flexbox layouts). The column width is dynamically calculated based on the number of columns and the gap size.

### mCols
- **Type:** `string`
- **Default:** `""`
- **Description:** Specifies the number of columns for mobile view (applies to flexbox layouts). The column width is dynamically calculated based on the number of columns and the gap size.

### className
- **Type:** `string`
- **Description:** Additional custom classes to be added to the container.

### children
- **Type:** `ReactNode`
- **Description:** The content to be rendered inside the container.

### extraProps
- **Type:** `object`
- **Description:** Additional props to be passed to the container's root element.

## `Container.Item` Props

### grow
- **Type:** `number`
- **Description:** Specifies how much a flex item should grow relative to the rest of the flex items.
    - `"0"`
    - `"1"`

### shrink
- **Type:** `number`
- **Description:** Specifies how much a flex item should shrink relative to the rest of the flex items.
    - `"0"`
    - `"1"`

### order
- **Type:** `string`
- **Description:** Defines the order of the flex item in the container.
    - `"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"`
    - `"first"`
    - `"last"`
    - `"none"`

### alignSelf
- **Type:** `string`
- **Description:** Allows the default alignment (or the one specified by align-items) to be overridden for individual flex items.
    - `"auto"`
    - `"start"`
    - `"end"`
    - `"stretch"`
    - `"baseline"`

## Usage

### Basic Example

```jsx
import { Container } from '@bsf/force-ui';

const App = () => (
    <>
        {/* Default Flex Behavior */}
        <Container justify="end" align="start" gap="xs" className="bg-orange-300 h-60">
            <Container.Item grow={1}>Item 1</Container.Item>
            <Container.Item>Item 2</Container.Item>
            <Container.Item grow={1}>Item 3</Container.Item>
        </Container>

        {/* Responsive Behavior */}
        <Container cols={4} tabCols={2} mCols={1} gap="md" className="bg-pink-200 p-4">
            <Container.Item className="bg-red-500 p-4">Item 1</Container.Item>
            <Container.Item className="bg-green-500 p-4">Item 2</Container.Item>
            <Container.Item className="bg-blue-500 p-4">Item 3</Container.Item>
            <Container.Item className="bg-yellow-500 p-4">Item 4</Container.Item>
        </Container>
    </>
);

export default App;
```

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-08-27 09:00 UTC, ravindra114 approved these changes
Tested! 
Attaching video below 

https://github.com/user-attachments/assets/ab4cf67c-e976-483c-b5cc-3bc44b6077c2

2024-08-27 09:01 UTC, vrundakansara requested changes

2024-08-27 09:01 UTC, vrundakansara commented on src/components/input/input.jsx
> -		if ( ! isControlled && type !== 'file' ) {
Why have we deleted this code?

2024-08-27 11:28 UTC, jaieds commented on src/components/container/container.jsx
>  import { cn } from '../../utilities/functions';
```suggestion
import { cn } from '@/utilities/functions';
```

2024-08-27 11:29 UTC, jaieds commented on src/components/container/container.jsx
> +	return gapMap[ gapClass ] || '1rem'; // Default to 1rem if not found
```suggestion
	return gapMap?.[ gapClass ] ?? '1rem'; // Default to 1rem if not found
```

2024-08-28 08:56 UTC, vrundakansara approved these changes

2024-08-28 09:07 UTC, jaieds commented on src/components/container/container.jsx
> +	}?.[ tabCols ] ?? 'w-1/2';
```suggestion
	}?.[ tabCols ] ?? 'md:w-1/2';
```

2024-08-28 09:07 UTC, jaieds commented on src/components/container/container.jsx
> +	}?.[ cols ] ?? 'w-1/4';
```suggestion
	}?.[ cols ] ?? 'lg:w-1/4';
```

2024-08-28 09:28 UTC, jaieds approved these changes

2024-08-28 09:41 UTC, merged