SUR-249 - Editor input component
brainstormforce/force-ui pull request #38
Opened 2024-08-26 13:34 UTC by jaieds

### Description

- Please check out the documentation [Readme.md](https://github.com/brainstormforce/force-ui/blob/75b9378fcb4e4ca7a26120667af36814ce63a0d3/src/components/editor-input/readme.md)

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:

-   [x] My code is tested
-   [ ] My code passes the PHPCS tests
-   [x] I've created the npm build.
-   [x] My code follows accessibility standards 
-   [x] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [x] I've included developer documentation 
-   [x] I've added proper labels to this pull request

2024-08-26 14:26 UTC, JelenaTakac commented
Is it allowed to set multiple instances of the same option? 👉 https://bsf.d.pr/i/kqgpEB

2024-08-26 14:28 UTC, JelenaTakac reviewed
Is it allowed to set multiple instances of the same option? 👉 https://bsf.d.pr/i/kqgpEB

2024-08-26 14:34 UTC, jaieds commented
> Is it allowed to set multiple instances of the same option? 👉 https://bsf.d.pr/i/kqgpEB

@JelenaTakac, Yes.

2024-08-27 07:40 UTC, vrundakansara requested changes

2024-08-27 07:42 UTC, jaieds commented on package.json
> +    "@emotion/is-prop-valid": "^1.3.0",
Yes. We need it for the `framer-motion` library. They are using this library to validate props.

2024-08-27 07:49 UTC, vrundakansara approved these changes

2024-08-27 08:45 UTC, JelenaTakac approved these changes
Tested.

2024-08-27 09:11 UTC, merged