SUR-256 Update tabs component as per new mockup
brainstormforce/force-ui pull request #46
Opened 2024-08-30 10:00 UTC by JelenaTakac

### Description

# Tabs Component Documentation

## Description

The `Tabs` component is a flexible and customizable component built with Tailwind CSS. It supports various orientations, variants, sizes, and additional properties to suit different use cases.

## Tabs.Group Props

### `orientation`
- **Type:** `string`
- **Default:** `"horizontal"`
- **Description:** Defines the orientation of the tabs. Options include:
  - `"horizontal"`
  - `"vertical"`

### `variant`
- **Type:** `string`
- **Default:** `"pill"`
- **Description:** Defines the style variant of the tabs. Options include:
  - `"pill"`
  - `"rounded"`
  - `"underline"`

### `size`
- **Type:** `string`
- **Default:** `"sm"`
- **Description:** Defines the size of the tabs. Options include:
  - `"xs"`
  - `"sm"`
  - `"md"`
  - `"lg"`

### `iconPosition`
- **Type:** `string`
- **Default:** `"left"`
- **Description:** Defines the position of the icon inside the tab. Options include:
  - `"left"`
  - `"right"`

### `className`
- **Type:** `string`
- **Description:** Additional custom classes to be added to the tabs.

### `width`
- **Type:** `string`
- **Default:** `"auto"`
- **Description:** Defines the width of the tabs. Options include:
  - `"auto"`
  - `"full"`

### `activeItem`
- **Type:** `string|null`
- **Default:** `null`
- **Description:** The currently active item in the group.

### `onChange`
- **Type:** `Function`
- **Description:** Callback when the active item changes.

### `children`
- **Type:** `ReactNode`
- **Description:** The content to be displayed inside the tabs.

## Tabs.Tab Props

### `slug`
- **Type:** `string`
- **Description:** Unique identifier for the tab.

### `text`
- **Type:** `string`
- **Description:** Text to be displayed inside the tab.

### `icon`
- **Type:** `ReactNode`
- **Description:** An optional icon to be displayed inside the tab.

### `className`
- **Type:** `string`
- **Description:** Additional custom classes to be added to the tab.

### `disabled`
- **Type:** `boolean`
- **Default:** `false`
- **Description:** Defines whether the tab is disabled.

### `badge`
- **Type:** `ReactNode`
- **Description:** An optional badge to be displayed alongside the tab text.

## Usage

### Basic Example

```jsx
import Tabs from './Tabs';
import { ReactComponent as ExampleIcon } from './icons/example.svg';

const App = () => (
  <div>
    <Tabs.Group variant="rounded" size="md" orientation="horizontal">
      <Tabs.Tab slug="tab1" text="Tab 1" icon={<ExampleIcon />} />
      <Tabs.Tab slug="tab2" text="Tab 2" icon={<ExampleIcon />} />
    </Tabs.Group>
  </div>
);

export default App;

### Screenshots

### Types of changes

### How has this been tested?

### Checklist:

-   [ ] My code is tested
-   [ ] My code passes the PHPCS tests
-   [ ] I've created the npm build.
-   [ ] My code follows accessibility standards 
-   [ ] My code has proper inline documentation 
-   [ ] I've included any necessary tests 
-   [ ] I've included developer documentation 
-   [ ] I've added proper labels to this pull request

2024-09-02 04:11 UTC, jaieds requested changes
UI not matching with the Figma mockup. 

👉 https://d.pr/i/HolCWo

2024-09-02 05:47 UTC, ravindra114 commented on src/components/tabs/tabs.jsx
> +		sm: variant === 'underline' ? 'py-1.5 text-sm [&>svg]:h-4 [&>svg]:w-4' : 'px-3 py-1.5 text-sm [&>svg]:h-4 [&>svg]:w-4',
You can use size-4 instead of [&>svg]:h-4 [&>svg]:w-4

2024-09-03 05:26 UTC, vrundakansara approved these changes

2024-09-03 05:30 UTC, jaieds commented on src/components/tabs/tabs.jsx
> +					? <span className="absolute right-0 left-0 -bottom-[1px] h-[1px] bg-border-interactive"></span>
```suggestion
					? <span className="absolute right-0 left-0 -bottom-px h-px bg-border-interactive"></span>
```

2024-09-03 05:31 UTC, jaieds commented on src/components/tabs/tabs.jsx
> +	const iconParentClasses = cn( 'flex items-center gap-1' );
```suggestion
	const iconParentClasses = 'flex items-center gap-1';
```

2024-09-03 05:33 UTC, jaieds commented on src/components/tabs/tabs.jsx
> +	const baseClasses = `relative border-none bg-transparent text-text-tertiary cursor-pointer flex items-center justify-center transition-colors duration-200 ${ fullWidth } ${ orientationClasses }`;
Try not to use Template string for class names, use the `cn` function instead.

2024-09-03 05:47 UTC, ravindra114 reviewed
I think on hover it should show background to tab?
![image](https://github.com/user-attachments/assets/ec22da14-ea0c-4764-b0b6-14e943aae69e)

not able to see this

https://github.com/user-attachments/assets/357fc092-688b-4857-8ab7-b13500b1c280

2024-09-03 09:42 UTC, jaieds requested changes
@JelenaTakac, Please check the screenshot 👉 https://d.pr/i/Rtcakc

2024-09-03 12:08 UTC, jaieds approved these changes

2024-09-03 12:45 UTC, merged